//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApiMagazine
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class dbRestosEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet dbRestosEntities à l'aide de la chaîne de connexion trouvée dans la section 'dbRestosEntities' du fichier de configuration d'application.
        /// </summary>
        public dbRestosEntities() : base("name=dbRestosEntities", "dbRestosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dbRestosEntities.
        /// </summary>
        public dbRestosEntities(string connectionString) : base(connectionString, "dbRestosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dbRestosEntities.
        /// </summary>
        public dbRestosEntities(EntityConnection connection) : base(connection, "dbRestosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Revue> Revues
        {
            get
            {
                if ((_Revues == null))
                {
                    _Revues = base.CreateObjectSet<Revue>("Revues");
                }
                return _Revues;
            }
        }
        private ObjectSet<Revue> _Revues;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Revues. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToRevues(Revue revue)
        {
            base.AddObject("Revues", revue);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbRestosModel", Name="Revue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Revue : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Revue.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        /// <param name="titre">Valeur initiale de la propriété Titre.</param>
        public static Revue CreateRevue(global::System.Int32 id, global::System.String titre)
        {
            Revue revue = new Revue();
            revue.Id = id;
            revue.Titre = titre;
            return revue;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titre
        {
            get
            {
                return _Titre;
            }
            set
            {
                OnTitreChanging(value);
                ReportPropertyChanging("Titre");
                _Titre = StructuralObject.SetValidValue(value, false, "Titre");
                ReportPropertyChanged("Titre");
                OnTitreChanged();
            }
        }
        private global::System.String _Titre;
        partial void OnTitreChanging(global::System.String value);
        partial void OnTitreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Exemplaires
        {
            get
            {
                return _Exemplaires;
            }
            set
            {
                OnExemplairesChanging(value);
                ReportPropertyChanging("Exemplaires");
                _Exemplaires = StructuralObject.SetValidValue(value, "Exemplaires");
                ReportPropertyChanged("Exemplaires");
                OnExemplairesChanged();
            }
        }
        private Nullable<global::System.Int16> _Exemplaires;
        partial void OnExemplairesChanging(Nullable<global::System.Int16> value);
        partial void OnExemplairesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prix
        {
            get
            {
                return _Prix;
            }
            set
            {
                OnPrixChanging(value);
                ReportPropertyChanging("Prix");
                _Prix = StructuralObject.SetValidValue(value, "Prix");
                ReportPropertyChanged("Prix");
                OnPrixChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prix;
        partial void OnPrixChanging(Nullable<global::System.Decimal> value);
        partial void OnPrixChanged();

        #endregion

    }

    #endregion

}
