//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("dbRestoModel", "FK_Critiques_ToResto", "Restos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcWC11.Resto), "Critiques", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcWC11.Critique), true)]

#endregion

namespace MvcWC11
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class dbRestoEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet dbRestoEntities à l'aide de la chaîne de connexion trouvée dans la section 'dbRestoEntities' du fichier de configuration d'application.
        /// </summary>
        public dbRestoEntities() : base("name=dbRestoEntities", "dbRestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dbRestoEntities.
        /// </summary>
        public dbRestoEntities(string connectionString) : base(connectionString, "dbRestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dbRestoEntities.
        /// </summary>
        public dbRestoEntities(EntityConnection connection) : base(connection, "dbRestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Critique> Critiques
        {
            get
            {
                if ((_Critiques == null))
                {
                    _Critiques = base.CreateObjectSet<Critique>("Critiques");
                }
                return _Critiques;
            }
        }
        private ObjectSet<Critique> _Critiques;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Resto> Restos
        {
            get
            {
                if ((_Restos == null))
                {
                    _Restos = base.CreateObjectSet<Resto>("Restos");
                }
                return _Restos;
            }
        }
        private ObjectSet<Resto> _Restos;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Critiques. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCritiques(Critique critique)
        {
            base.AddObject("Critiques", critique);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Restos. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToRestos(Resto resto)
        {
            base.AddObject("Restos", resto);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbRestoModel", Name="Critique")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(CritiqueMetaData))]
    public partial class Critique : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Critique.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        public static Critique CreateCritique(global::System.Int32 id)
        {
            Critique critique = new Critique();
            critique.Id = id;
            return critique;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Texte
        {
            get
            {
                return _Texte;
            }
            set
            {
                OnTexteChanging(value);
                ReportPropertyChanging("Texte");
                _Texte = StructuralObject.SetValidValue(value, true, "Texte");
                ReportPropertyChanged("Texte");
                OnTexteChanged();
            }
        }
        private global::System.String _Texte;
        partial void OnTexteChanging(global::System.String value);
        partial void OnTexteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, "Note");
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private Nullable<global::System.Int16> _Note;
        partial void OnNoteChanging(Nullable<global::System.Int16> value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pseudo
        {
            get
            {
                return _Pseudo;
            }
            set
            {
                OnPseudoChanging(value);
                ReportPropertyChanging("Pseudo");
                _Pseudo = StructuralObject.SetValidValue(value, true, "Pseudo");
                ReportPropertyChanged("Pseudo");
                OnPseudoChanged();
            }
        }
        private global::System.String _Pseudo;
        partial void OnPseudoChanging(global::System.String value);
        partial void OnPseudoChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RestoId
        {
            get
            {
                return _RestoId;
            }
            set
            {
                OnRestoIdChanging(value);
                ReportPropertyChanging("RestoId");
                _RestoId = StructuralObject.SetValidValue(value, "RestoId");
                ReportPropertyChanged("RestoId");
                OnRestoIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RestoId;
        partial void OnRestoIdChanging(Nullable<global::System.Int32> value);
        partial void OnRestoIdChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbRestoModel", "FK_Critiques_ToResto", "Restos")]
        public Resto Resto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resto>("dbRestoModel.FK_Critiques_ToResto", "Restos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resto>("dbRestoModel.FK_Critiques_ToResto", "Restos").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Resto> RestoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resto>("dbRestoModel.FK_Critiques_ToResto", "Restos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Resto>("dbRestoModel.FK_Critiques_ToResto", "Restos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbRestoModel", Name="Resto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Resto : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Resto.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        public static Resto CreateResto(global::System.Int32 id)
        {
            Resto resto = new Resto();
            resto.Id = id;
            return resto;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, true, "Nom");
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodePostal
        {
            get
            {
                return _CodePostal;
            }
            set
            {
                OnCodePostalChanging(value);
                ReportPropertyChanging("CodePostal");
                _CodePostal = StructuralObject.SetValidValue(value, true, "CodePostal");
                ReportPropertyChanged("CodePostal");
                OnCodePostalChanged();
            }
        }
        private global::System.String _CodePostal;
        partial void OnCodePostalChanging(global::System.String value);
        partial void OnCodePostalChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ville
        {
            get
            {
                return _Ville;
            }
            set
            {
                OnVilleChanging(value);
                ReportPropertyChanging("Ville");
                _Ville = StructuralObject.SetValidValue(value, true, "Ville");
                ReportPropertyChanged("Ville");
                OnVilleChanged();
            }
        }
        private global::System.String _Ville;
        partial void OnVilleChanging(global::System.String value);
        partial void OnVilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Photo
        {
            get
            {
                return _Photo;
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true, "Photo");
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.String _Photo;
        partial void OnPhotoChanging(global::System.String value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value, "DateCreation");
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreation;
        partial void OnDateCreationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreationChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbRestoModel", "FK_Critiques_ToResto", "Critiques")]
        public EntityCollection<Critique> Critiques
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Critique>("dbRestoModel.FK_Critiques_ToResto", "Critiques");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Critique>("dbRestoModel.FK_Critiques_ToResto", "Critiques", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="dbRestoModel", Name="Adress")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Adress : ComplexObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Adress.
        /// </summary>
        /// <param name="rue">Valeur initiale de la propriété Rue.</param>
        /// <param name="vilkle">Valeur initiale de la propriété Vilkle.</param>
        /// <param name="codePostal">Valeur initiale de la propriété CodePostal.</param>
        public static Adress CreateAdress(global::System.String rue, global::System.String vilkle, global::System.String codePostal)
        {
            Adress adress = new Adress();
            adress.Rue = rue;
            adress.Vilkle = vilkle;
            adress.CodePostal = codePostal;
            return adress;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rue
        {
            get
            {
                return _Rue;
            }
            set
            {
                OnRueChanging(value);
                ReportPropertyChanging("Rue");
                _Rue = StructuralObject.SetValidValue(value, false, "Rue");
                ReportPropertyChanged("Rue");
                OnRueChanged();
            }
        }
        private global::System.String _Rue;
        partial void OnRueChanging(global::System.String value);
        partial void OnRueChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Vilkle
        {
            get
            {
                return _Vilkle;
            }
            set
            {
                OnVilkleChanging(value);
                ReportPropertyChanging("Vilkle");
                _Vilkle = StructuralObject.SetValidValue(value, false, "Vilkle");
                ReportPropertyChanged("Vilkle");
                OnVilkleChanged();
            }
        }
        private global::System.String _Vilkle;
        partial void OnVilkleChanging(global::System.String value);
        partial void OnVilkleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodePostal
        {
            get
            {
                return _CodePostal;
            }
            set
            {
                OnCodePostalChanging(value);
                ReportPropertyChanging("CodePostal");
                _CodePostal = StructuralObject.SetValidValue(value, false, "CodePostal");
                ReportPropertyChanged("CodePostal");
                OnCodePostalChanged();
            }
        }
        private global::System.String _CodePostal;
        partial void OnCodePostalChanging(global::System.String value);
        partial void OnCodePostalChanged();

        #endregion

    }

    #endregion

}
